<?php

namespace MPM\Bundle\PagosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MesPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesPagoRepository extends EntityRepository
{
}
