<?php

namespace MPM\Bundle\PagosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReglaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglaRepository extends EntityRepository
{
}
