<?php

namespace MPM\Bundle\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TarifaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifaRepository extends EntityRepository
{
}
